<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Developer;
use File;

class DevelopersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public static function run()
    {
        $json = File::get(__DIR__ . "/data/developers.json");

        $developers = json_decode($json);

        Developer::create([
            'name_en' => '[Unknown]',
            'name_it' => '[Unknown]',
            'description_en' => 'This developer is generated by the system and is used for games whose developer is not known.',
            'description_it' => 'Questo sviluppatore è generato dal sistema ed è usato per quei giochi il cui sviluppatore è sconosciuto.',
            'approved' => true
        ]);

        foreach ($developers as $developer) {
            Developer::create([
                'name_en' => $developer->name,
                'name_it' => $developer->name,
                'link_en' => trim($developer->link ?? ''),
                'link_it' => trim($developer->link ?? ''),
                'approved' => true
            ]);
        }
    }
}
