<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Publisher;
use File;

class PublishersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public static function run()
    {
        $json = File::get(__DIR__ . "/data/publishers.json");

        $publishers = json_decode($json);

        Publisher::create([
            'name_en' => '[Unknown]',
            'name_it' => '[Unknown]',
            'description_en' => 'This publisher is generated by the system and is used for games whose publisher is not known.',
            'description_it' => 'Questo editore è generato dal sistema ed è usato per quei giochi il cui editore è sconosciuto.',
            'approved' => true
        ]);

        foreach ($publishers as $publisher) {
            dd ($publisher->link);
            Publisher::create([
                'name_en' => $publisher->name,
                'name_it' => $publisher->name,
                'link' => trim($publisher->link ?? ''),
                'approved' => true
            ]);
        }
    }
}
